### ISSUE TITLE
UI 

### ISSUE THREAD

**Issue by fescii** [teau-ict-club/club-website#24]
Elements are not responsive

**Comment by Chal13W1zz** [comment]
Thank you for letting us know @fescii, we'll work on that.

**Comment by fescii** [comment]
@Chal13W1zz  The header should be sticky to allow smooth navigation, also the site logo is too large, perhaps you should consider using a text or a minimal/SVG logo..
Also can I freely create/merge a pull request?

**Comment by Chal13W1zz** [comment]
Sure, feel free to fork the project and contribute, we're rolling out an update before EOD today. The broken navigation links have been on our to-do list. But feel free to chip in.
